In [1]:
import pandas as pd
import numpy as np
import os

In [3]:
os.listdir('Extracted Datasets')

['Combined_Data.csv',
 'loc6_combined.csv',
 'temp_bio_data.csv',
 'temp_phy_data.csv']

In [6]:
combined = pd.read_csv('Extracted Datasets/Combined_Data.csv')
loc6 = pd.read_csv('Extracted Datasets/loc6_combined.csv')

In [22]:
combined.mean().round(6)

spco2          36.981963
o2            235.536241
chl             0.159008
latitude        8.202819
no3             3.777984
po4             0.316071
phyc            1.306461
si              5.291371
ph              8.060772
nppv            3.344338
longitude     -35.801096
fe              0.000509
mlotst         37.873536
siconc          0.000000
thetao         20.899030
usi             0.000000
sithick         0.000001
bottomT         1.967186
vsi             0.000000
vo              0.014845
uo              0.031496
so             34.783922
zos             0.120807
year         2005.864526
month           6.500000
dtype: float64

In [15]:
combined

,time,spco2,o2,chl,latitude,no3,po4,phyc,si,ph,...,usi,sithick,bottomT,vsi,vo,uo,so,zos,year,month
0,2000-01,31.765936,213.97511,0.093244,22.0,0.004902,0.002215,0.993661,3.913857,8.122389,...,0.0,0.0,3.910612,0.0,0.023804,0.027467,35.818050,0.018006,2000,1
1,2000-02,31.911985,215.47520,0.086183,22.0,0.004318,0.002608,1.007598,4.055500,8.121443,...,0.0,0.0,3.905483,0.0,-0.187384,0.064089,35.827206,-0.096438,2000,2
2,2000-03,33.540830,212.93338,0.088064,22.0,0.006213,0.000848,1.284753,4.300098,8.103570,...,0.0,0.0,3.895229,0.0,-0.126347,0.177007,35.885190,-0.102847,2000,3
3,2000-04,35.236195,208.32628,0.088673,22.0,0.005149,0.000352,1.415458,4.893192,8.085176,...,0.0,0.0,3.893764,0.0,0.093997,0.156255,36.095768,-0.211798,2000,4
4,2000-05,37.714030,202.40598,0.089608,22.0,0.004710,0.000139,1.501259,5.088798,8.060551,...,0.0,0.0,3.894497,0.0,0.088504,-0.020753,36.219368,-0.168767,2000,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168559,2018-08,37.748978,276.01200,0.339174,-40.0,10.462052,0.853391,1.311569,5.452005,8.056345,...,0.0,0.0,0.652698,0.0,0.085452,0.039674,34.298225,-0.139164,2018,8
168560,2018-09,37.884846,266.17800,0.363841,-40.0,9.436721,0.771441,1.259476,4.557523,8.056080,...,0.0,0.0,0.730339,0.0,0.068361,0.051881,34.160892,-0.156560,2018,9
168561,2018-10,38.285090,278.11404,0.350610,-40.0,10.440707,0.846379,2.008195,6.022601,8.052111,...,0.0,0.0,0.783808,0.0,-0.101932,-0.075076,34.575947,-0.105594,2018,10
168562,2018-11,39.373806,277.29007,0.277200,-40.0,10.290730,0.863582,1.889477,5.894831,8.042534,...,0.0,0.0,0.738396,0.0,-0.006104,-0.299692,35.294655,0.040895,2018,11
168563,2018-12,40.665688,269.14752,0.300080,-40.0,9.855226,0.853065,1.828403,5.648209,8.030845,...,0.0,0.0,0.640247,0.0,0.050661,-0.131230,35.323650,0.025025,2018,12